import type { MapRegion } from './types'

export const mapRegions: MapRegion[] = [
  {
    id: 'knossos',
    name: 'Кносс',
    x: 56,
    y: 51,
    region: 'greece',
    description: 'Минойская цивилизация, Крит. 2000–1375 гг. до н. э.',
  },
  {
    id: 'mycenae',
    name: 'Микены',
    x: 53,
    y: 49,
    region: 'greece',
    description: 'Ахейские цари. 1600–1100 гг. до н. э.',
  },
  {
    id: 'athens',
    name: 'Афины',
    x: 54,
    y: 48,
    region: 'greece',
    description: 'Парфенон, Акрополь. V в. до н. э.',
  },
  {
    id: 'sparta',
    name: 'Спарта',
    x: 54,
    y: 50,
    region: 'greece',
    description: 'Военный полис Лаконики.',
  },
  {
    id: 'olympia',
    name: 'Олимпия',
    x: 52,
    y: 50,
    region: 'greece',
    description: 'Олимпийские игры с 776 г. до н. э.',
  },
  {
    id: 'delphi',
    name: 'Дельфы',
    x: 53,
    y: 48,
    region: 'greece',
    description: 'Оракул Аполлона. Омфалос.',
  },
  {
    id: 'rome',
    name: 'Рим',
    x: 48,
    y: 44,
    region: 'rome',
    description: 'Колизей, Пантеон, Форум.',
  },
  {
    id: 'pompeii',
    name: 'Помпеи',
    x: 50,
    y: 45,
    region: 'rome',
    description: 'Засыпан Везувием в 79 г. н. э.',
  },
  {
    id: 'byzantium',
    name: 'Константинополь',
    x: 58,
    y: 43,
    region: 'rome',
    description: 'Святая София, Феодосиевы стены.',
  },
  {
    id: 'ur',
    name: 'Ур',
    x: 64,
    y: 47,
    region: 'mesopotamia',
    description: 'Шумер. Зиккурат 2100 г. до н. э.',
  },
  {
    id: 'babylon',
    name: 'Вавилон',
    x: 64,
    y: 45,
    region: 'mesopotamia',
    description: 'Хаммурапи, Навуходоносор II, Ворота Иштар.',
  },
  {
    id: 'nineveh',
    name: 'Ниневия',
    x: 65,
    y: 43,
    region: 'mesopotamia',
    description: 'Столица Ассирии. Библиотека Ашшурбанапала.',
  },
  {
    id: 'panticapaeum',
    name: 'Пантикапей (Керчь)',
    x: 60,
    y: 38,
    region: 'kuban',
    description: 'Столица Боспорского царства.',
  },
  {
    id: 'phanagoria',
    name: 'Фанагория',
    x: 61,
    y: 39,
    region: 'kuban',
    description: 'Тамань. Второй город Боспора.',
  },
  {
    id: 'gorgippia',
    name: 'Горгиппия (Анапа)',
    x: 59,
    y: 39,
    region: 'kuban',
    description: 'Центр виноделия Боспора.',
  },
  {
    id: 'chersonesos-map',
    name: 'Херсонес (Севастополь)',
    x: 58,
    y: 37,
    region: 'kuban',
    description: 'Полис, основан в 422 г. до н. э. Крещение Владимира 988 г.',
  },
  {
    id: 'olbia-map',
    name: 'Ольвия',
    x: 56,
    y: 36,
    region: 'kuban',
    description: 'Милетская колония в устье Южного Буга. VII в. до н. э.',
  },
  {
    id: 'alexandria-map',
    name: 'Александрия',
    x: 58,
    y: 50,
    region: 'greece',
    description: 'Маяк, Библиотека, Мусейон. Основана в 331 г. до н. э.',
  },
]
